baseURL = "https://nbaztec.me"
title = "nbaztec"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[markup.goldmark.renderer]
unsafe= true

[params]
author = "Nisheeth Barthwal"
description = "Nisheeth Barthwal's personal website"
keywords = "blog,developer,personal"
info = ["Software Engineer"]
avatarURL = "images/me.jpg"
#gravatar = "nbaztec@gmail.com"
dateFormat = "January 2, 2006"
since = 2022
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/nbaztec/nbaztec/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "dark"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = [ "/css/override.css" ]
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []
favicon_32 = "images/nb.png"
favicon_16 = "images/nb.png"
touchicon = "images/nb.png"

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
# [params.googleTagManager]
# id = "gid"

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/", "https://kit.fontawesome.com", "https://ka-f.fontawesome.com"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = ["'self'", "'unsafe-inline'", "https://www.google-analytics.com", "https://kit.fontawesome.com", "https://ka-f.fontawesome.com"]
prefetchsrc = ["'self'"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com", "https://kit.fontawesome.com", "https://ka-f.fontawesome.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/nbaztec/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/nbaztec/"

[[params.social]]
name = "Medium"
icon = "fa fa-2x fa-medium"
weight = 5
url = "https://medium.com/@nbaztec"

[[params.programming.0]]
name = "Golang"
icon = "devicon-go-original-wordmark colored"
weight = 1

[[params.programming.0]]
name = "Rust"
icon = "devicon-rust-plain colored"
weight = 2

[[params.programming.0]]
name = "NodeJS"
icon = "devicon-nodejs-plain colored"
weight = 3

[[params.programming.0]]
name = "Typescript"
icon = "devicon-typescript-plain colored"
weight = 4
hide = true

[[params.programming.0]]
name = "Kotlin"
icon = "devicon-kotlin-plain colored"
image = "images/logos/kotlin.svg"
weight = 5
hide = true

[[params.programming.0]]
name = "Angular"
icon = "devicon-angularjs-plain colored"
weight = 6

[[params.programming.1]]
name = "AWS"
icon = "devicon-amazonwebservices-plain-wordmark colored"
image = "images/logos/aws.svg"
weight = 1

[[params.programming.1]]
name = "Google Cloud"
image = "images/logos/gcp.svg"
weight = 1

[[params.programming.1]]
name = "Kubernetes"
icon = "devicon-kubernetes-plain colored"
weight = 1

[[params.programming.1]]
name = "etcd"
image = "images/logos/etcd.svg"
weight = 1
hide = true

[[params.programming.1]]
name = "Prometheus"
image = "images/logos/prometheus.svg"
weight = 1


[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[languages.en.menu.main.params]
newTarget = false
