[build]
publish = "public"
command = "hugo --gc --minify --enableGitInfo"

[build.environment]
HUGO_VERSION = "0.91.2"
HUGO_THEME = "hugo-coder"

[context.deploy-preview]
command = "hugo --buildFuture --buildDrafts"
