[build]
publish = "nbaztec/public"
command = "hugo --baseURL $URL"

[build.environment]
HUGO_VERSION = "0.91.2"
HUGO_THEME = "hugo-coder"

[context.deploy-preview]
command = "hugo --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL"
